### PR TITLE
New: Completion icon added to transcript button (issue/33)

### LINKED ISSUE #33: Add completed checkmark for transcript to match the media component
### Subject of the issue/enhancement/features
With the recent change to the media component to have a completed checkmark for the transcript buttons,
(see here: https://github.com/adaptlearning/adapt-contrib-media/issues/290)
The same should be done for the vimeo and youtube components as they are specialised versions of the media component.
This issue in particular focuses on the youtube component

### Expected behaviour
After interacting with the transcript button a check should appear

### Screenshots (if you can)
image

### PR DESCRIPTION
**Pull request by lemmyadams**
Addresses #33

### CODE REVIEW

**Review by ethan-lp — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by guywillis** [comment]
Would this be an opportune time to mimic the updates to the Vimeo plugin to keep the two plugins in sync?

Reference: https://github.com/adaptlearning/adapt-vimeo/pull/36

**Review by joe-allen-89 — APPROVED** [review]
👍

**Comment by oliverfoster** [comment]
> Would this be an opportune time to mimic the updates to the Vimeo plugin to keep the two plugins in sync?
> 
> Reference: [adaptlearning/adapt-vimeo#36](https://github.com/adaptlearning/adapt-vimeo/pull/36)

It looks as though most of those things are in this plugin already. Was there any specific parts you had noticed were missing?

https://github.com/adaptlearning/adapt-vimeo/blob/724d4e75c29d146c26af8c4d0fd0cc1b51c8211f/js/adapt-vimeo.js
https://github.com/adaptlearning/adapt-youtube/blob/cacae8699461da180f263259843f0a52a1051d31/js/YouTubeView.js

**Comment by guywillis** [comment]
Yes. Specifically for the inline icon:

* There isn't a plus icon in this PR which exists in the Media and Vimeo plugins - https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-47282ddbfde7fce64096a7bedacf2aee53b4846825c476fb38b41ec7fe8ada9aR50-R52

But I also noticed: 

* There's variance in the `onSkipToTranscript` function and subsequent toggle inline / external transcript functions https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-27c9e7d21edb3f1c67a0f614d84edbf4d18ea5b172f55ec5e468fb4010a2e9f0R104
* There's a small chunk of accessibility related CSS in the Vimeo plugin but missing from the YouTube plugin - https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-47282ddbfde7fce64096a7bedacf2aee53b4846825c476fb38b41ec7fe8ada9aR18-R33
* The skip to transcript button html is different in the vimeo version - https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-df6113c1175800ec9c8161c5600ce4c9f2a2d7974783c7ac16c55889a1f458edR7-R9
* The inline transcript template has some variance in comparison to the youtube version - https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-df6113c1175800ec9c8161c5600ce4c9f2a2d7974783c7ac16c55889a1f458edR19-R25
* The `vimeo__transcript-body-inline` aria label has difference - https://github.com/adaptlearning/adapt-vimeo/pull/36/files#diff-df6113c1175800ec9c8161c5600ce4c9f2a2d7974783c7ac16c55889a1f458edR47-R53

**Comment by lemmyadams** [comment]
I don't really know anything about those changes I can copy and paste it across

**Comment by lemmyadams** [comment]
@guywillis I've updated it now to match Vimeo from your comments, could you have a review please?

**Review by ethan-lp — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👍  

Thank you

**Pull request merged**
