### PR TITLE
adds various bit of functionality

### PR DESCRIPTION
**Pull request by moloko**
* proper transcript support
* ~skip to transcript option~
* play, pause and ended events (as per https://github.com/adaptlearning/adapt_framework/issues/2344)
* configuration for player controls & fullscreen
* proper use of ComponentModel (as per https://github.com/adaptlearning/adapt_framework/issues/1179)

plus a bit of a general tidy-up

### CODE REVIEW

**Comment by moloko** [comment]
haven't actually tested this yet, just getting the PR setup - will test properly next week

also note there further improvements to come such as switching over to use the new core `inview` functionality and a11y updates; I've left these for now so that we can do one more Adapt v2 compatible release first

**Comment by danielstorey** [comment]
Hey @moloko,

In advance of starting on the Vimeo Component I was chatting with Ollie and we were talking about having a core Transcript View so I wonder if it's worth creating an abstracted view at this point so it can be moved over to core at some point and to avoid duplicating between Media, YouTube and Vimeo.

I'm also keen on abstracting the actual video views from the component view, and also moving these into core/libraries at some point so they can be used by other components/plugins and all have the same API.  I.e wouldn't it be nice if we could do
```
var videoView;
switch(videoType) {
  case 'youtube':
    videoView = new YouTubeView();
    break;
  case 'video':
    videoView = new VimeoView();
    break;
  case 'html5': default:
    videoView = new HTML5VideoView();
    break;
}

videoView.on('play', handlePlay);
videoView.play();
```

I don't know if you think this is worth doing at this stage though...?

**Comment by moloko** [comment]
@danielstorey these updates are designed to be compatible with FW 2&3 so anything like that wouldn't be applicable here.

I definitely agree it would be worth creating a TranscriptView in core, probably as part of some kind of MediaView that could easily be extended by plugins.

**Comment by oliverfoster** [comment]
Just as an aside to the TranscriptView/MediaView implementation. In v6 we'll hopefully have plugin dependencies and the core will be a series of hierarchically stacked/replaceable plugins providing sub-systems for utilisation by other plugins. Any opportunity to create a reliable version of a commonly used behaviour should be taken. At the moment, in lieu of dependent sub-systems, those behaviours should be created in the core adapt_framework - we can then separate them out into separate parts in v6.

**Comment by moloko** [comment]
have dropped the 'skip to transcript' functionality as I realised it really needs the `any` handlebars helper to work - and that's not available in FW v.2.x

I'll add this back in properly with the next update (which will drop support for FW v2.x)

Ready to review now if anyone wants to?

**Comment by moloko** [comment]
last call for reviews! otherwise I'll merge tomorrow and get started on an FW4 compatible version

**Pull request merged**
